# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03e3f433581e9e3d24ceb8ae810d7c3f2db0d393c4b793db7c05c9a6e0b608765d7dbb2b603ad7aca915843f7c255a80df8c97e598de89a98252e213add3cd62

test:
  secret_key_base: f2df55230c575970b7e7d64d04a8d1b947ec56c3f0ade540bec003a6f847ee5e8e72b8afbc1f8385e95af201e166108a8961dda0e9c771f0e56ebacaec574240

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
